version: '3'

volumes:
    postgres:

services:
    postgres:
        image: postgres
        restart: unless-stopped
        volumes:
            - postgres:/var/lib/postgresql/data
            - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
        environment:
            - POSTGRES_USER=springentity
            - POSTGRES_PASSWORD=pass
            - POSTGRES_DB=springdb
              #healthcheck:
              #test: ["CMD-SHELL", "pg_isready -U springentity"]
              #interval: 5s
              #timeout: 5s
              #retries: 5
        ports:
            - 5432:5432
    springproj:
        build:
            context: .
        image: akopalips/springproj:0.0.1
        environment:
            - TZ=Asia/Krasnoyarsk
            - _JAVA_OPTIONS=-Dlogging.level.root=DEBUG
        ports:
            - 8080:8080
              #depends_on:
              #postgres:
              #  condition: service_healthy
        links:
            - postgres
