version: '3'

volumes:
    postgres:

services:
    postgres:
        image: postgres
        restart: unless-stopped
        volumes:
            - postgres:/var/lib/postgresql/data
            - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
        environment:
            - POSTGRES_USER=springentity
            - POSTGRES_PASSWORD=pass
            - POSTGRES_DB=jdbc:springdb
        ports:
            - 5432:5432


    springproj:
        build:
            context: .
        image: akopalips/springproj:0.0.1
        environment:
            - TZ=Asia/Krasnoyarsk
            - _JAVA_OPTIONS=-Dlogging.level.root=DEBUG
            - SPRING_DATASOURCE_URL="jdbc:postgresql://postgres:5432/springdb"
        ports:
            - 8080:8080
        links:
            - postgres